src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/WorkspaceDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/model/WorkspaceModel.scala
src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
src/main/scala/org/broadinstitute/dsde/rawls/ws/PerRequest.scala
src/main/scala/org/broadinstitute/dsde/rawls/ws/RawlsApiService.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/WorkspaceDAOSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceServiceSpec.scala

also fixed PerRequest actor to marshall responses correctly

implemented workspace list

---

src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/WorkspaceDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/model/WorkspaceModel.scala
src/main/scala/org/broadinstitute/dsde/rawls/webservice/RawlsApiService.scala
src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/WorkspaceDAOSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceServiceSpec.scala

POST /workspaces/namespace/name/clone
body:
{ "namespace" : foo, "name" : bar }

Clone workspace endpoint

---

src/main/scala/org/broadinstitute/dsde/rawls/Boot.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/FileSystemWorkspaceDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphEntityDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphWorkspaceDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/WorkspaceDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/model/WorkspaceModel.scala
src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/FileSystemWorkspaceDAOSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphEntityDAOSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphWorkspaceDAOSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/graph/OrientDbTestFixture.scala
src/test/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceApiServiceSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceServiceSpec.scala

First stab at a graph DAO using Tinkerpop and OrientDB. Also cleaned up the dataaccess package. 
Does not include: using remote DB server, smart transactions.

Graph DAO with tests

---

src/main/scala/org/broadinstitute/dsde/rawls/Boot.scala
src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala

Also fix typo in EntityUpdateModel

Point at orientdb-dev

---

build.sbt
src/it/resources/application.conf
src/it/scala/org/broadinstitute/dsde/rawls/Timer.scala
src/it/scala/org/broadinstitute/dsde/rawls/WorkspaceGenerator.scala
src/it/scala/org/broadinstitute/dsde/rawls/WorkspaceSimulation.scala
src/test/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceApiServiceSpec.scala

Integration test framework to simulate realistic use cases for the workspace service. Includes random data generation, timing, and a pretty simple simulation to start us off.
Integration tests go in ```src/it``` and are run with ```sbt it:test```, as per SBT conventions.

Integration test framework

---

src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphEntityDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphWorkspaceDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/model/WorkspaceModel.scala
src/main/scala/org/broadinstitute/dsde/rawls/webservice/PerRequest.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphEntityDAOSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphWorkspaceDAOSpec.scala

Removed the ~10 warnings that pop up at compilation

Removed compilation warnings

---

src/it/scala/org/broadinstitute/dsde/rawls/WorkspaceSimulation.scala

Three things:
* Allow test config to be pulled from ```jenkins.conf``` instead of ```/etc/rawls.conf``` (makes things much easier for Jenkins)
* Update method config route to reflect current API
* Increase scale by factor of 10, since integration tests seem to run much faster on Jenkins than locally

Make integration tests work

---

src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphEntityDAOSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphMethodConfigDAOSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceApiServiceSpec.scala

Use sets to avoid ordering issues in unit tests

---

build.sbt
src/main/scala/org/broadinstitute/dsde/rawls/jobexec/MethodConfigValidator.scala
src/test/scala/org/broadinstitute/dsde/rawls/jobexec/MethodConfigValidatorSpec.scala

Preliminary PR. This part is independent from Ted's stuff, so can be reviewed before that is merged.

Validation

---

src/it/scala/org/broadinstitute/dsde/rawls/IntegrationTestBase.scala
src/it/scala/org/broadinstitute/dsde/rawls/IntegrationTestConfig.scala
src/it/scala/org/broadinstitute/dsde/rawls/RemoteServicesSpec.scala
src/it/scala/org/broadinstitute/dsde/rawls/WorkspaceSimulation.scala
src/main/scala/org/broadinstitute/dsde/rawls/Boot.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/ExecutionServiceDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/HttpExecutionServiceDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/HttpMethodRepoDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/MethodRepoDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/model/WorkspaceModel.scala
src/main/scala/org/broadinstitute/dsde/rawls/webservice/JobApiService.scala
src/main/scala/org/broadinstitute/dsde/rawls/webservice/RawlsApiService.scala
src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
src/test/scala/org/broadinstitute/dsde/rawls/mock/MethodRepoMockServer.scala
src/test/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceApiServiceSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceServiceSpec.scala

This requires further changes to rawls.conf -- so don't merge until that's done.

submitJob endpoint

---

build.sbt
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphEntityDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/expressions/ExpressionParsing.scala
src/main/scala/org/broadinstitute/dsde/rawls/model/WorkspaceModel.scala
src/main/scala/org/broadinstitute/dsde/rawls/webservice/EntityApiService.scala
src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
src/test/scala/org/broadinstitute/dsde/rawls/expressions/JexlTest.scala
src/test/scala/org/broadinstitute/dsde/rawls/expressions/RhinoTest.scala
src/test/scala/org/broadinstitute/dsde/rawls/expressions/RhinoTest2.scala
src/test/scala/org/broadinstitute/dsde/rawls/expressions/SimpleExpressionParser.scala
src/test/scala/org/broadinstitute/dsde/rawls/graph/OrientDbTestFixture.scala
src/test/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceApiServiceSpec.scala

Many commits got squished to bring you this pull request.
I'm leaving the Jexl and Rhino tests in for now, but we'll want to clean them up once we pick a solution for complex expressions.

Added simple expression parsing, rooted at a given entity

---

src/it/scala/org/broadinstitute/dsde/rawls/RemoteServicesSpec.scala
src/it/scala/org/broadinstitute/dsde/rawls/WorkspaceSimulation.scala
src/main/scala/org/broadinstitute/dsde/rawls/Boot.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/ExecutionServiceDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphSubmissionDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/HttpExecutionServiceDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/HttpMethodRepoDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/SubmissionDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/model/ExecutionModel.scala
src/main/scala/org/broadinstitute/dsde/rawls/model/JsonSupport.scala
src/main/scala/org/broadinstitute/dsde/rawls/model/MethodRepoModel.scala
src/main/scala/org/broadinstitute/dsde/rawls/model/WorkspaceModel.scala
src/main/scala/org/broadinstitute/dsde/rawls/webservice/JobApiService.scala
src/main/scala/org/broadinstitute/dsde/rawls/webservice/RawlsApiService.scala
src/main/scala/org/broadinstitute/dsde/rawls/webservice/SubmissionApiService.scala
src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/SubmissionDAOSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/mock/RemoteServicesMockServer.scala
src/test/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceApiServiceSpec.scala

Submission, Workflow, and CRUD API defined

model objects for Submission and Workflow with CRUD

---

.gitignore
src/main/resources/application.conf
src/main/scala/org/broadinstitute/dsde/rawls/Boot.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/ExecutionServiceDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphEntityDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphSubmissionDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/HttpExecutionServiceDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/SubmissionDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/jobexec/SubmissionMonitor.scala
src/main/scala/org/broadinstitute/dsde/rawls/jobexec/SubmissionSupervisor.scala
src/main/scala/org/broadinstitute/dsde/rawls/jobexec/WorkflowMonitor.scala
src/main/scala/org/broadinstitute/dsde/rawls/model/ExecutionModel.scala
src/test/resources/logback.xml
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/SubmissionDAOSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/graph/OrientDbTestFixture.scala
src/test/scala/org/broadinstitute/dsde/rawls/jobexec/SubmissionMonitorSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/jobexec/WorkflowMonitorSpec.scala

see here for the initial design
https://broadinstitute.atlassian.net/wiki/display/DSDEEPB/Monitoring+of+Cromwell+with+Actors

implemented submission and workflow monitoring

---

src/it/scala/org/broadinstitute/dsde/rawls/IntegrationTestBase.scala
src/it/scala/org/broadinstitute/dsde/rawls/IntegrationTestConfig.scala

Necessary to match the other secretsFile -> secrets changes

Update GCS secrets access

---

src/it/scala/org/broadinstitute/dsde/rawls/IntegrationTestBase.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GoogleCloudStorageDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/model/GoogleBucketACL.scala
src/main/scala/org/broadinstitute/dsde/rawls/model/UserInfo.scala
src/main/scala/org/broadinstitute/dsde/rawls/openam/OpenAmDirectives.scala
src/main/scala/org/broadinstitute/dsde/rawls/openam/StandardOpenAmDirectives.scala
src/main/scala/org/broadinstitute/dsde/rawls/webservice/EntityApiService.scala
src/main/scala/org/broadinstitute/dsde/rawls/webservice/GoogleAuthApiService.scala
src/main/scala/org/broadinstitute/dsde/rawls/webservice/MethodConfigApiService.scala
src/main/scala/org/broadinstitute/dsde/rawls/webservice/RawlsApiService.scala
src/main/scala/org/broadinstitute/dsde/rawls/webservice/SubmissionApiService.scala
src/main/scala/org/broadinstitute/dsde/rawls/webservice/WorkspaceApiService.scala
src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/MockGoogleCloudStorageDAO.scala
src/test/scala/org/broadinstitute/dsde/rawls/graph/OrientDbTestFixture.scala
src/test/scala/org/broadinstitute/dsde/rawls/jobexec/SubmissionSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/mock/MockACLs.scala
src/test/scala/org/broadinstitute/dsde/rawls/openam/MockOpenAmDirectives.scala
src/test/scala/org/broadinstitute/dsde/rawls/workspace/GoogleAuthApiServiceSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceApiServiceSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceServiceSpec.scala

~~TODO: Test against actual GCS Bucket ACLs!  It's possible their JSON format doesn't match this code.~~
~~Does not cover the Submission endpoints.~~
Does not cover endpoints for which we need Project ACLs rather than Bucket ACLs, like Create Workspace and Clone Workspace.
Does not cover List Workspaces.

Restrict routes by GCS Bucket ACLs

---

src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/EntityDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/model/AttributeUpdateOperations.scala
src/main/scala/org/broadinstitute/dsde/rawls/model/WorkspaceModel.scala
src/main/scala/org/broadinstitute/dsde/rawls/webservice/EntityApiService.scala
src/main/scala/org/broadinstitute/dsde/rawls/webservice/WorkspaceApiService.scala
src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
src/test/scala/org/broadinstitute/dsde/rawls/integrationtest/WorkspaceGenerator.scala
src/test/scala/org/broadinstitute/dsde/rawls/integrationtest/WorkspaceSimulation.scala
src/test/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceApiServiceSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceServiceSpec.scala

Before merging, I'd like to test POSTing some json with upsert instructions in swagger, but there are Google authentication problems preventing me from doing that at the moment. Other than that, this is ready for comments/complaints.

Added batch upsert to WorkspaceService and corresponding API endpoint

---

src/main/resources/swagger/api-docs
src/main/resources/swagger/index.html
src/main/resources/swagger/listings/authentication
src/main/resources/swagger/listings/entities
src/main/resources/swagger/listings/methodconfigs
src/main/resources/swagger/listings/submissions
src/main/resources/swagger/listings/workspaces
src/main/scala/org/broadinstitute/dsde/rawls/Boot.scala
src/main/scala/org/broadinstitute/dsde/rawls/model/ExecutionModel.scala
src/main/scala/org/broadinstitute/dsde/rawls/model/MethodRepoModel.scala
src/main/scala/org/broadinstitute/dsde/rawls/model/VaultModel.scala
src/main/scala/org/broadinstitute/dsde/rawls/model/WorkspaceModel.scala
src/main/scala/org/broadinstitute/dsde/rawls/webservice/EntityApiService.scala
src/main/scala/org/broadinstitute/dsde/rawls/webservice/GoogleAuthApiService.scala
src/main/scala/org/broadinstitute/dsde/rawls/webservice/MethodConfigApiService.scala
src/main/scala/org/broadinstitute/dsde/rawls/webservice/RawlsApiService.scala
src/main/scala/org/broadinstitute/dsde/rawls/webservice/SubmissionApiService.scala
src/main/scala/org/broadinstitute/dsde/rawls/webservice/WorkspaceApiService.scala
src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
src/test/scala/org/broadinstitute/dsde/rawls/integrationtest/RemoteServicesSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/integrationtest/WorkspaceSimulation.scala
src/test/scala/org/broadinstitute/dsde/rawls/workspace/GoogleAuthApiServiceSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceApiServiceSpec.scala

* Removed all swagger api annotations from code
* Refactored how API routes are called
* Added json files that can be modified to reflect new api changes
* Fixed inconsistencies in the API that did not properly reflect actual API calls
* Added missing status code responses and fixed inconsistent ones
* Added more json models that swagger previously couldn't generate automatically
Swagger configuration can be removed from rawls.conf

removed swagger annotations from code / created static swagger api

---

src/main/resources/swagger/listings/entities
src/main/resources/swagger/listings/methodconfigs

forgot to fix 2 paths in methodconfigs and also added properties to models in entities which will be used in the future

fixed methodconfig paths and entity model

---

src/main/scala/org/broadinstitute/dsde/rawls/RawlsException.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphEntityDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphMethodConfigurationDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphSubmissionDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphWorkspaceDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/webservice/PerRequest.scala
src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphEntityDAOSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphSubmissionDAOSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphWorkspaceDAOSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceApiServiceSpec.scala

Also rename ```SubmissionDAOSpec``` -> ```GraphSubmissionDAOSpec``` , since that's what it is.

Disallow dot in user defined strings

---

src/main/resources/swagger/listings/entities
src/main/scala/org/broadinstitute/dsde/rawls/webservice/EntityApiService.scala
src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
src/test/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceApiServiceSpec.scala

Like upsert except that the entities have to exist already.
Required by DSDEEPB-937.

Added batchUpdate endpoint, 

---

src/main/scala/org/broadinstitute/dsde/rawls/model/ExecutionModel.scala
src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
src/test/scala/org/broadinstitute/dsde/rawls/graph/OrientDbTestFixture.scala

This ends up being necessarty for DSDEEPB-438 but I wanted to pull it out into a separate commit.

Added submitting user to submissions

---

src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/HttpExecutionServiceDAO.scala
src/test/scala/org/broadinstitute/dsde/rawls/jobexec/SubmissionSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/mock/RemoteServicesMockServer.scala
src/test/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceApiServiceSpec.scala

endpoint and the inputs being called wdlSource, workflowInputs and not
wdl and inputs.

Fixed issues with submitting to Cromwell due to missing version on the

---

src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/WorkspaceApiServiceSpec.scala

Resolves https://broadinstitute.atlassian.net/browse/DSDEEPB-1071

reveal that which exists, but cannot be changed

---

src/main/scala/org/broadinstitute/dsde/rawls/Boot.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphContainerDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/jobexec/SubmissionMonitor.scala
src/main/scala/org/broadinstitute/dsde/rawls/jobexec/SubmissionSupervisor.scala
src/main/scala/org/broadinstitute/dsde/rawls/jobexec/WorkflowMonitor.scala
src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
src/test/scala/org/broadinstitute/dsde/rawls/graph/OrientDbTestFixture.scala
src/test/scala/org/broadinstitute/dsde/rawls/integrationtest/IntegrationTestBase.scala
src/test/scala/org/broadinstitute/dsde/rawls/jobexec/SubmissionMonitorSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/jobexec/SubmissionSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/jobexec/WorkflowMonitorSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/EntityApiServiceSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/GoogleAuthApiServiceSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/MethodConfigApiServiceSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/SubmissionApiServiceSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/WorkspaceApiServiceSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceServiceSpec.scala

somehow the other one got closed while i was trying to squash. oops.
doug's comments from the previous PR have been addressed in this one.

created GraphContainerDAO to hold all graph related DAOs

---

src/main/scala/org/broadinstitute/dsde/rawls/Boot.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/HttpGoogleCloudStorageDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/webservice/WorkspaceApiService.scala
src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
src/test/scala/org/broadinstitute/dsde/rawls/integrationtest/HttpGoogleCloudStorageDAOSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/WorkspaceApiServiceSpec.scala

Spooooky! You've [seen this one before](https://github.com/broadinstitute/rawls/pull/89).
I still don't know what to do about testing the bucket deletion stuff. I haven't even tested it manually. Thoughts?

DSDEEPB-764 Delete workspace includes deleting bucket and googroups

---

src/main/resources/application.conf
src/test/resources/application.conf

Should fix the build failures on master.

Fix logger timeouts

---

src/main/resources/swagger/listings/workspaces
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GoogleCloudStorageDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphWorkspaceDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/HttpGoogleCloudStorageDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/WorkspaceDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/jobexec/SubmissionMonitor.scala
src/main/scala/org/broadinstitute/dsde/rawls/model/WorkspaceModel.scala
src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/MockGoogleCloudStorageDAO.scala
src/test/scala/org/broadinstitute/dsde/rawls/integrationtest/HttpGoogleCloudStorageDAOSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/WorkspaceApiServiceSpec.scala

~~do not merge yet. I'd like Doug to look over this when he gets back because I had a hell of a time re-basing this branch and it looks like I messed something up along the way. All of the tests pass but listing workspaces is broken with this exception:~~
~~```"exception": "java.lang.IllegalArgumentException",
"message": "Type error. The class submissionEdge does not extend class 'E' and therefore cannot be considered an Edge",```~~
This is a combo PR for [DSDEEPB-526](https://broadinstitute.atlassian.net/browse/DSDEEPB-526) and [DSDEEPB-567](https://broadinstitute.atlassian.net/browse/DSDEEPB-567) since they were intertwined tasks and me and Doug worked off of the same branch for it. 
~~__TODO__ before merge: Finish updating the swagger json. Other than that, the contents of this are …

more detailed workspace reports and filter via acls

---

src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/ExecutionServiceDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/HttpExecutionServiceDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/jobexec/MethodConfigResolver.scala
src/main/scala/org/broadinstitute/dsde/rawls/model/ExecutionModel.scala
src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
src/test/scala/org/broadinstitute/dsde/rawls/jobexec/MethodConfigResolverSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/jobexec/WorkflowMonitorSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/mock/RemoteServicesMockServer.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/MethodConfigApiServiceSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/SubmissionApiServiceSpec.scala

New PR for https://broadinstitute.atlassian.net/browse/DSDEEPB-661
(replaces https://github.com/broadinstitute/rawls/pull/101)

method config validation

---

src/main/resources/swagger/listings/workspaces
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/HttpGoogleCloudStorageDAO.scala

swagger for delete workspaces seems to have been forgotten

---

CONTRIBUTING.md

comment on changes to the markdown as you see fit.
This would show up as a link as shown on this page:
https://github.com/blog/1184-contributing-guidelines
- repeat as necessary:
* Rest of team may comment on PR at will
* Further commits. DO NOT SQUASH. **Reassign to LR**
* Update documentation as needed
* **LR assigns to submitter**
* Re-rebase to master.

CONTRIBUTING.md file for PR guidelines check list

---

src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphDAO.scala

This is not a fix for all of DSDEEPB-1139 but it does fix an issue where it fails to understand that `WorkflowStatus` is a subclass of `RawlsEnumeration`.

Fix for sometimes failing to load rawlsenum types

---

src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphWorkspaceDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/WorkspaceDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala

kill isLocked

---

src/main/scala/org/broadinstitute/dsde/rawls/jobexec/MethodConfigResolver.scala
src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
src/test/scala/org/broadinstitute/dsde/rawls/jobexec/MethodConfigResolverSpec.scala

Resolves https://broadinstitute.atlassian.net/browse/DSDEEPB-1198.
I don't really like this solution, so feel free to take this sad branch and make it better.
- repeat as necessary:
* Rest of team may comment on PR at will
* Further commits. DO NOT SQUASH. **Reassign to LR**
* Update documentation as needed
* **LR assigns to submitter**
* Re-rebase to master.

Use SubmissionValidationValue in MethodConfigResolver

---

src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphWorkspaceDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/WorkspaceContext.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/WorkspaceDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphWorkspaceDAOSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/EntityApiServiceSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/WorkspaceApiServiceSpec.scala

just put the dang Workspace into the WorkspaceContext object -- it's always loaded anyway

---

src/main/scala/org/broadinstitute/dsde/rawls/expressions/ExpressionParsing.scala
src/test/scala/org/broadinstitute/dsde/rawls/expressions/SimpleExpressionParserTest.scala

Minimal changes for the story; not addressing the larger issues in the "Expression parsing error behavior" conversation.

DSDEEPB-1159: enable AttributeValueList

---

src/test/scala/org/broadinstitute/dsde/rawls/expressions/SimpleExpressionParserTest.scala

Workspace Entity Expressions were added recently (DSDEEPB-1136) but not tested.

Add tests for Workspace Entity Expressions

---

src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphEntityDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphWorkspaceDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/expressions/ExpressionParsing.scala
src/main/scala/org/broadinstitute/dsde/rawls/model/WorkspaceModel.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphEntityDAOSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphWorkspaceDAOSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/expressions/SimpleExpressionParserTest.scala

added reserved attribute names and get them from vertex properties in expressions

---

src/main/scala/org/broadinstitute/dsde/rawls/model/ExecutionModel.scala
src/test/scala/org/broadinstitute/dsde/rawls/jobexec/SubmissionSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/jobexec/WorkflowMonitorSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/mock/RemoteServicesMockServer.scala

Resolves DSDEEPB-1211.  Handles non-scatter/gathered logs too because they are returned as single-element lists.

Cromwell logs are now a sequence of stdout/stderr pairs

---

src/main/resources/swagger/listings/methodconfigs
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/HttpMethodRepoDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/MethodRepoDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/jobexec/MethodConfigResolver.scala
src/main/scala/org/broadinstitute/dsde/rawls/model/WorkspaceModel.scala
src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphMethodConfigDAOSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/graph/OrientDbTestFixture.scala
src/test/scala/org/broadinstitute/dsde/rawls/integrationtest/RemoteServicesSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/integrationtest/WorkspaceGenerator.scala
src/test/scala/org/broadinstitute/dsde/rawls/jobexec/MethodConfigResolverSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/mock/RemoteServicesMockServer.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/MethodConfigApiServiceSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/SubmissionApiServiceSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/WorkspaceApiServiceSpec.scala

*Probably* don't merge this yet. We'd like to see if it breaks old data first.
https://broadinstitute.atlassian.net/browse/DSDEEPB-1250
This PR is to create consistency between rawls and agora.

Switched methodconfig version number from string to int

---

src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/ExecutionServiceDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/HttpExecutionServiceDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/model/ExecutionModel.scala
src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
src/test/scala/org/broadinstitute/dsde/rawls/jobexec/SubmissionSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/jobexec/WorkflowMonitorSpec.scala

DSDEEPB-854 feed workflow options to cromwell to tell it where to put workflow outputs

tell cromwell where to stick it

---

src/main/resources/swagger/listings/workspaces
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GoogleCloudStorageDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphWorkspaceDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/HttpGoogleCloudStorageDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/WorkspaceDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/model/WorkspaceModel.scala
src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphEntityDAOSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphWorkspaceDAOSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/MockGoogleCloudStorageDAO.scala
src/test/scala/org/broadinstitute/dsde/rawls/integrationtest/HttpGoogleCloudStorageDAOSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/jobexec/SubmissionSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/WorkspaceApiServiceSpec.scala

group names based on bucket UUID

---

build.sbt
src/main/resources/swagger/index.html
src/main/resources/swagger/rawls.yaml
src/main/scala/org/broadinstitute/dsde/rawls/webservice/RawlsApiService.scala

The conversion exposed a bunch of validation errors that I fixed as best I could but there may be some lingering issues. If you need help splitting this into multiple files just let me know.
This should be all set to add oauth security definitions and secure the endpoints.
Required an update to the latest swagger ui.

Converted 1.2 to 2.0. All one file for now.

---

src/main/resources/swagger/listings/submissions
src/main/scala/org/broadinstitute/dsde/rawls/jobexec/MethodConfigResolver.scala
src/main/scala/org/broadinstitute/dsde/rawls/model/ExecutionModel.scala
src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
src/test/scala/org/broadinstitute/dsde/rawls/jobexec/SubmissionSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/SubmissionApiServiceSpec.scala

addresses DSDEEPB-1110
- [ x] **Submitter**: Rebase to master. DO NOT SQUASH
- [ x] **Submitter**: Make sure Swagger is updated if API changes
- [ x] **Submitter**: Make sure documentation for code is complete
- [ x] **Submitter**: Review code comments; remove done TODOs, create stories for remaining TODOs
- [ x] **Submitter**: Include the JIRA issue number in the PR description
- [ x] **Submitter**: Add description or comments on the PR explaining the hows/whys (if not obvious)
- [ x] **Submitter**: **Assign PR to** ![](http://i.imgur.com/9dLzbPd.png)
* Submitter makes further commits. DO NOT SQUASH. …

improve submission error messages

---

src/main/resources/swagger/rawls.yaml
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/ExecutionServiceDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/HttpExecutionServiceDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/model/ExecutionModel.scala
src/main/scala/org/broadinstitute/dsde/rawls/webservice/SubmissionApiService.scala
src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
src/test/scala/org/broadinstitute/dsde/rawls/jobexec/SubmissionSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/jobexec/WorkflowMonitorSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/mock/RemoteServicesMockServer.scala

pass-thru to cromwell for call-level metadata

---

src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphMethodConfigurationDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/model/WorkspaceModel.scala
src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/MethodConfigApiServiceSpec.scala

For DSDEEPB-821.  Will need to coordinate deployment with Silver for their DSDEEPB-1342.

Validate Method Config input and output attributes

---

src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GoogleCloudStorageDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/HttpGoogleCloudStorageDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/MockGoogleCloudStorageDAO.scala
src/test/scala/org/broadinstitute/dsde/rawls/integrationtest/HttpGoogleCloudStorageDAOSpec.scala

fix the way we set ACLs on buckets

---

src/main/resources/swagger/rawls.yaml
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/HttpMethodRepoDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/MethodRepoDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/model/WorkspaceModel.scala
src/main/scala/org/broadinstitute/dsde/rawls/webservice/MethodConfigApiService.scala
src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
src/test/scala/org/broadinstitute/dsde/rawls/graph/OrientDbTestFixture.scala
src/test/scala/org/broadinstitute/dsde/rawls/integrationtest/IntegrationTestConfig.scala
src/test/scala/org/broadinstitute/dsde/rawls/integrationtest/RemoteServicesSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/mock/RemoteServicesMockServer.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/MethodConfigApiServiceSpec.scala

https://broadinstitute.atlassian.net/browse/DSDEEPB-422

implemented copy method config to agora

---

src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala

This PR is for [DSDEEPB-1373](https://broadinstitute.atlassian.net/browse/DSDEEPB-1373) and also contains a few related changes for rolling back any operations that result in a bad request within a transaction. 

roll back operations that fail

---

src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/HttpGoogleCloudStorageDAO.scala

Somewhat addresses DSDEEPB-1134.
I can't think of anything else to do to improve this further, other than to pass back word of what went wrong on the Google calls.  (But that's a different story.)  Happy to receive reviewers' suggestions for further improvements.

try to restore user's former status on failed ACL updates

---

src/main/resources/swagger/rawls.yaml
src/main/scala/org/broadinstitute/dsde/rawls/Boot.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GoogleServicesDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphSubmissionDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/HttpGoogleServicesDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/SubmissionDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/model/ExecutionModel.scala
src/main/scala/org/broadinstitute/dsde/rawls/webservice/AdminApiService.scala
src/main/scala/org/broadinstitute/dsde/rawls/webservice/RawlsApiService.scala
src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/MockGoogleServicesDAO.scala
src/test/scala/org/broadinstitute/dsde/rawls/integrationtest/HttpGoogleServicesDAOSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/integrationtest/IntegrationTestBase.scala
src/test/scala/org/broadinstitute/dsde/rawls/jobexec/SubmissionSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/mock/RemoteServicesMockServer.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/AdminApiServiceSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/EntityApiServiceSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/MethodConfigApiServiceSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/SubmissionApiServiceSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/WorkspaceApiServiceSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceServiceSpec.scala

work in progress on admin endpoints

---

src/main/resources/swagger/rawls.yaml

found some bugs in my swagger yaml
can someone just take a quick look and hit the merge button, please?

found some oopsies

---

src/main/resources/swagger/rawls.yaml
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/jobexec/MethodConfigResolver.scala
src/main/scala/org/broadinstitute/dsde/rawls/model/WorkspaceModel.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphMethodConfigDAOSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/graph/OrientDbTestFixture.scala
src/test/scala/org/broadinstitute/dsde/rawls/integrationtest/RemoteServicesSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/integrationtest/WorkspaceGenerator.scala
src/test/scala/org/broadinstitute/dsde/rawls/jobexec/MethodConfigResolverSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/MethodConfigApiServiceSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/SubmissionApiServiceSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/WorkspaceApiServiceSpec.scala

Addresses Rawls part of DSDEEPB-1343

eliminate references to method repo configuration

---

src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphEntityDAO.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphEntityDAOSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/graph/OrientDbTestFixture.scala

This PR solves two separate bugs related to [DSDEEPB-1389](https://broadinstitute.atlassian.net/browse/DSDEEPB-1389).
The first was related to listEntitiesAllTypes, which would break if there were no entities in the workspace. This is the problem that silver team was running into. Upon fixing that, a second problem was uncovered. The second problem was more significant and the fix for that has been extracted from Hussein's mummified PR #114, particularly [this commit](https://github.com/broadinstitute/rawls/commit/2e6fde0bc0d360e141bcd393b542ada6779155b7).
* Submitter makes further commits. DO NOT SQUASH. …

Fix copy entities

---

src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphSubmissionDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/jobexec/SubmissionMonitor.scala

Minor changes not related to a story.  Merge if you like them.

Small fixes

---

src/main/resources/swagger/rawls.yaml
src/main/scala/org/broadinstitute/dsde/rawls/webservice/MethodConfigApiService.scala
src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/MethodConfigApiServiceSpec.scala

This is in support of [DSDEEPB-511](https://broadinstitute.atlassian.net/browse/DSDEEPB-511). Added an endpoint to GET syntax validation information for a method configuration.

added validation endpoint for method configs

---

src/main/resources/swagger/index.html
src/main/resources/swagger/rawls.yaml
src/main/scala/org/broadinstitute/dsde/rawls/webservice/RawlsApiService.scala

[DSDEEPB-1470](https://broadinstitute.atlassian.net/browse/DSDEEPB-1470)
This should make our swagger work on http://swagger.dsde-dev.broadinstitute.org/. Also added a route filter that returns a 200 OK for all options requests. This was apparently required in order for this swagger change to work.
* Rest of team may comment on PR at will

Fix swagger to work with central swagger UI

---

src/main/resources/swagger/rawls.yaml
src/main/scala/org/broadinstitute/dsde/rawls/model/WorkspaceModel.scala
src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphDAODeleteSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphEntityDAOSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphWorkspaceDAOSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/MockGoogleServicesDAO.scala
src/test/scala/org/broadinstitute/dsde/rawls/graph/OrientDbTestFixture.scala
src/test/scala/org/broadinstitute/dsde/rawls/jobexec/MethodConfigResolverSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/jobexec/SubmissionSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/WorkspaceApiServiceSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceServiceSpec.scala

For [DSDEEPB-1510](https://broadinstitute.atlassian.net/browse/DSDEEPB-1510).
**note: it looks like adding this field will break all of the data currently in orient so we should coordinate with silver before merging**

Add workspace bucketName to response and case class

---

src/main/resources/swagger/rawls.yaml
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/DataSource.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/ExecutionServiceDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GoogleServicesDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphWorkspaceDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/HttpExecutionServiceDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/HttpGoogleServicesDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/HttpMethodRepoDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/MethodRepoDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/Retry.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/WorkspaceContext.scala
src/main/scala/org/broadinstitute/dsde/rawls/expressions/ExpressionParsing.scala
src/main/scala/org/broadinstitute/dsde/rawls/jobexec/WorkflowMonitor.scala
src/main/scala/org/broadinstitute/dsde/rawls/util/FutureSupport.scala
src/main/scala/org/broadinstitute/dsde/rawls/webservice/PerRequest.scala
src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/MockGoogleServicesDAO.scala
src/test/scala/org/broadinstitute/dsde/rawls/integrationtest/HttpGoogleServicesDAOSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/jobexec/SubmissionSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/jobexec/WorkflowMonitorSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/AdminApiServiceSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/MethodConfigApiServiceSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/WorkspaceApiServiceSpec.scala

DSDEEPB-1374 gets rid of blocking code by reformulating any functionality that accesses a http dao in terms of Futures. This is practically everything because we need to access google groups for access control info. This means that essentially all operations start with a Future and do some transformation (map, flatMap, recover, etc) to that Future to produce another Future(s). The final Future is "piped" to the PerRequest actor which handles the response when the Future is complete. Note that we never use Future.onComplete as exceptions in those callbacks are unhandled.
* Submitter makes further commits. DO …

using Futures to remove blocking code

---

src/main/resources/swagger/rawls.yaml
src/main/scala/org/broadinstitute/dsde/rawls/model/ExecutionModel.scala

For [DSDEEPB-1553](https://broadinstitute.atlassian.net/browse/DSDEEPB-1553), which is a blocker for Silver team. 
Here's a screenshot of the output of the fixed endpoint. I'm not 100% sure what this is supposed to look like, but Alex and Miguel said that it looked reasonable. Nothing really changed to the case class except for adding a field and renaming some fields.

fixed call-level metadata case class to match cromwell

---

src/main/resources/swagger/rawls.yaml
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GoogleServicesDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/HttpGoogleServicesDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/MockGoogleServicesDAO.scala
src/test/scala/org/broadinstitute/dsde/rawls/integrationtest/HttpGoogleServicesDAOSpec.scala

For https://broadinstitute.atlassian.net/browse/DSDEEPB-1567

prevent users from changing their own permissions

---

src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/DataSource.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphWorkspaceDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/jobexec/SubmissionMonitor.scala
src/main/scala/org/broadinstitute/dsde/rawls/model/WorkspaceModel.scala
src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphDAODeleteSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphEntityDAOSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphMethodConfigDAOSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphSubmissionDAOSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphWorkspaceDAOSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/expressions/SimpleExpressionParserTest.scala
src/test/scala/org/broadinstitute/dsde/rawls/graph/OrientDbTestFixture.scala
src/test/scala/org/broadinstitute/dsde/rawls/jobexec/MethodConfigResolverSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/jobexec/SubmissionMonitorSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/jobexec/SubmissionSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/EntityApiServiceSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/MethodConfigApiServiceSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/WorkspaceApiServiceSpec.scala

DSDEEPB-1310 "Big hammer" workspace locking

---

build.sbt
src/main/scala/org/broadinstitute/dsde/rawls/Boot.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/DataSource.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/HttpGoogleServicesDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/Retry.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/WorkspaceContext.scala
src/main/scala/org/broadinstitute/dsde/rawls/util/FutureSupport.scala
src/main/scala/org/broadinstitute/dsde/rawls/webservice/AdminApiService.scala
src/main/scala/org/broadinstitute/dsde/rawls/webservice/EntityApiService.scala
src/main/scala/org/broadinstitute/dsde/rawls/webservice/MethodConfigApiService.scala
src/main/scala/org/broadinstitute/dsde/rawls/webservice/PerRequest.scala
src/main/scala/org/broadinstitute/dsde/rawls/webservice/RawlsApiService.scala
src/main/scala/org/broadinstitute/dsde/rawls/webservice/SubmissionApiService.scala
src/main/scala/org/broadinstitute/dsde/rawls/webservice/WorkspaceApiService.scala
src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
src/test/scala/org/broadinstitute/dsde/rawls/TestExecutionContext.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/DataSourceSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/graph/OrientDbTestFixture.scala
src/test/scala/org/broadinstitute/dsde/rawls/integrationtest/HttpGoogleServicesDAOSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/integrationtest/IntegrationTestBase.scala
src/test/scala/org/broadinstitute/dsde/rawls/integrationtest/RemoteServicesSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/integrationtest/WorkspaceSimulation.scala
src/test/scala/org/broadinstitute/dsde/rawls/jobexec/SubmissionSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/AdminApiServiceSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/EntityApiServiceSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/MethodConfigApiServiceSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/SubmissionApiServiceSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/WorkspaceApiServiceSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceServiceSpec.scala

https://broadinstitute.atlassian.net/browse/DSDEEPB-1155
The main changes here were in the google tests to auth and await correctly and in the Workspace simulation to auth correctly. A bunch of files were changed to make the execution context a parameter so we can control it centrally and have a different one in tests. Then there were a few places added to make the correct connection active and other things that were helpful in debugging.

Fix integration tests

---

src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/DataSource.scala

DSDEEPB-1633 Moved ObamaLocks to JVM locks because Orient refuses to lock remote databases

---

src/main/resources/swagger/rawls.yaml
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/ExecutionServiceDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GoogleServicesDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/HttpGoogleServicesDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/MethodRepoDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/jobexec/SubmissionMonitor.scala
src/main/scala/org/broadinstitute/dsde/rawls/model/WorkspaceModel.scala
src/main/scala/org/broadinstitute/dsde/rawls/webservice/PerRequest.scala
src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/MockGoogleServicesDAO.scala
src/test/scala/org/broadinstitute/dsde/rawls/jobexec/SubmissionSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/EntityApiServiceSpec.scala

chain sub-service exceptions, clean up error reporting

---

src/main/resources/swagger/rawls.yaml
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphWorkspaceDAO.scala
src/main/scala/org/broadinstitute/dsde/rawls/model/WorkspaceModel.scala
src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphDAODeleteSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphEntityDAOSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/dataaccess/GraphWorkspaceDAOSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/graph/OrientDbTestFixture.scala
src/test/scala/org/broadinstitute/dsde/rawls/jobexec/MethodConfigResolverSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/jobexec/SubmissionSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/WorkspaceApiServiceSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceServiceSpec.scala

https://broadinstitute.atlassian.net/browse/DSDEEPB-1559

add lastModified field to Workspace case class

---

src/main/scala/org/broadinstitute/dsde/rawls/jobexec/SubmissionMonitor.scala
src/test/scala/org/broadinstitute/dsde/rawls/graph/OrientDbTestFixture.scala
src/test/scala/org/broadinstitute/dsde/rawls/jobexec/SubmissionMonitorSpec.scala
src/test/scala/org/broadinstitute/dsde/rawls/webservice/SubmissionApiServiceSpec.scala

DSDEEPB-1581 Putting workflow outputs on workspaces or entities depending on expressions
